apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forgemind.fullname" . }}-env
  labels:
    {{- include "forgemind.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "forgemind.envContent" . | nindent 4 }}
